### ISSUE TITLE
spelling issue..

### ISSUE THREAD

**Issue by BlackFoxgamingstudio** [MicrosoftDocs/azure-gaming-docs#1]
"Azure Container Instances (ACI) - Everything is managed by your but in a container, it needs a custom scaling solution"

"Everything is managed by your but in a container"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa270af-945c-857e-e991-597a0ed1126e
* Version Independent ID: 0783d9dd-145e-4c36-35e0-99df7fbfd2e0
* Content: [Multiplayer Backend Reference Architectures - Azure Gaming](https://docs.microsoft.com/en-us/gaming/azure/reference-architectures/multiplayer#feedback)
* Content Source: [azure-gaming-pr/reference-architectures/multiplayer.md](https://github.com/MicrosoftDocs/azure-gaming-docs/blob/docs/azure-gaming-pr/reference-architectures/multiplayer.md)
* Service: **azure**
* GitHub Login: @BrianPeek
* Microsoft Alias: **brpeek**

**Comment by BrianPeek** [comment]
Fixed in recent PR, thanks!
