### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mcsnotty** [MicrosoftDocs/azure-gaming-docs#3]
Right after "Azure Traffic Manager" - Cconnects 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a0c6da-0bdb-fc95-07ef-a258918b3480
* Version Independent ID: 9b6833a5-3fe9-4f05-a0df-4587dd430d43
* Content: [Multiplayer Game Server Hosting Using AKS - Azure Gaming](https://docs.microsoft.com/en-us/gaming/azure/reference-architectures/multiplayer-synchronous-aks#feedback)
* Content Source: [azure-gaming-pr/reference-architectures/multiplayer-synchronous-aks.md](https://github.com/MicrosoftDocs/azure-gaming-docs/blob/docs/azure-gaming-pr/reference-architectures/multiplayer-synchronous-aks.md)
* Product: **azure-gaming**
* GitHub Login: @BrianPeek
* Microsoft Alias: **brpeek**

**Comment by BrianPeek** [comment]
Fixed, thanks!
