### ISSUE TITLE
Unreal Pixel Streaming: Broken link to Unreal Engine docs

### ISSUE THREAD

**Issue by Structed** [MicrosoftDocs/azure-gaming-docs#34]
The first link to "Getting Started" on the Unreal Engine Docs is broken.

I assume it should point to: https://docs.unrealengine.com/5.0/en-US/pixel-streaming-in-unreal-engine/

![image](https://user-images.githubusercontent.com/29922/177794648-b5386e38-01fe-42e0-94fa-b159df9e4a8f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f69a8ab7-b113-ed24-d144-5ffc03af4de4
* Version Independent ID: f69a8ab7-b113-ed24-d144-5ffc03af4de4
* Content: [Unreal Pixel Streaming in Azure - Azure Gaming](https://docs.microsoft.com/en-us/gaming/azure/reference-architectures/unreal-pixel-streaming-in-azure)
* Content Source: [azure-gaming-pr/reference-architectures/unreal-pixel-streaming-in-azure.md](https://github.com/MicrosoftDocs/azure-gaming-docs/blob/docs/azure-gaming-pr/reference-architectures/unreal-pixel-streaming-in-azure.md)
* Product: **azure-gaming**
* GitHub Login: @BenHumphrey
* Microsoft Alias: **behumphr**

**Comment by microsoftman** [comment]
Hi @Structed, the Getting Started link works for me, and redirects to the Getting Started walkthrough on Epic's page, this link doesn't redirect for you? https://docs.unrealengine.com/en-US/Platforms/PixelStreaming/PixelStreamingIntro/index.html should redirect to https://docs.unrealengine.com/5.0/en-US/getting-started-with-pixel-streaming-in-unreal-engine/
