### ISSUE TITLE
Netstat and Telnet test not applicable on Bedrock servers

### ISSUE THREAD

**Issue by cpyne** [MicrosoftDocs/azure-gaming-docs#5]
On my working Bedrock server, netstat shows the following for 19132.      

UDP    0.0.0.0:19132          *:*

No "listening" status since this is just for TCP.   It also doesn't appear that you can telnet to a UDP port to test connectivity.   The test at the end of the article should clarify tests for Bedrock vs Java

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d93d01e-a461-735f-956a-59b9e761fa48
* Version Independent ID: b704a57d-691c-8541-8829-0cac2b3411bd
* Content: [Basic Game Server Hosting - Azure Gaming](https://docs.microsoft.com/en-us/gaming/azure/reference-architectures/multiplayer-basic-game-server-hosting#feedback)
* Content Source: [azure-gaming-pr/reference-architectures/multiplayer-basic-game-server-hosting.md](https://github.com/MicrosoftDocs/azure-gaming-docs/blob/docs/azure-gaming-pr/reference-architectures/multiplayer-basic-game-server-hosting.md)
* Product: **azure-gaming**
* GitHub Login: @BrianPeek
* Microsoft Alias: **brpeek**

**Comment by BrianPeek** [comment]
This will be fixed in an update going live soon.  Thank you!
