### ISSUE TITLE
Azure Marketplace Minecraft Server offering no longer available

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/azure-gaming-docs#6]
In the additional resources section, the page linked as "Deploying a Minecraft Server using the Azure Marketplace Minecraft Server offering" states that it this offering is no longer available due to actions by Microsoft.  I'd suggest removing the link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d93d01e-a461-735f-956a-59b9e761fa48
* Version Independent ID: b704a57d-691c-8541-8829-0cac2b3411bd
* Content: [Basic Game Server Hosting - Azure Gaming](https://docs.microsoft.com/en-us/gaming/azure/reference-architectures/multiplayer-basic-game-server-hosting)
* Content Source: [azure-gaming-pr/reference-architectures/multiplayer-basic-game-server-hosting.md](https://github.com/MicrosoftDocs/azure-gaming-docs/blob/docs/azure-gaming-pr/reference-architectures/multiplayer-basic-game-server-hosting.md)
* Product: **azure-gaming**
* GitHub Login: @BrianPeek
* Microsoft Alias: **brpeek**

**Comment by BrianPeek** [comment]
This will be fixed in an update going live soon.  Thank you!
